apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: poc-deployment
spec:
  selector:
    matchLabels:
      app: poc
  replicas: 4 # tells deployment to run 4 pods matching the template
  template:
    metadata:
      labels:
        app: poc
    spec:
      containers:
      - name: poc
        image: shivani26071997/poc_image1
        ports:
        - containerPort: 8010
      restartPolicy: Always